export const AUTHENTICATION_LOGIN_REQUEST = 'AUTHENTICATION_LOGIN_REQUEST';

export const AUTHENTICATION_LOGIN_SUCCESS = 'AUTHENTICATION_LOGIN_SUCCESS';

export const AUTHENTICATION_LOGIN_FAILURE = 'AUTHENTICATION_LOGIN_FAILURE';

export const STORE_CREDENTIALS_SUCCESS = 'STORE_CREDENTIALS_SUCCESS';

export const GET_BALANCE_REQUEST = 'GET_BALANCE_REQUEST';

export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';

export const GET_BALANCE_FAILURE = 'GET_BALANCE_FAILURE';

export const GET_EXCHANGE_REQUEST = 'GET_EXCHANGE_REQUEST';

export const GET_EXCHANGE_SUCCESS = 'GET_EXCHANGE_SUCCESS';

export const GET_EXCHANGE_FAILURE = 'GET_EXCHANGE_FAILURE';

export const GET_ADDRESSES_REQUEST = 'GET_ADDRESSES_REQUEST';

export const GET_ADDRESSES_SUCCESS = 'GET_ADDRESSES_SUCCESS';

export const GET_ADDRESSES_FAILURE = 'GET_ADDRESSES_FAILURE';

export const ADD_ADDRESSES_REQUEST = 'ADD_ADDRESSES_REQUEST';

export const ADD_ADDRESSES_SUCCESS = 'ADD_ADDRESSES_SUCCESS';

export const ADD_ADDRESSES_FAILURE = 'ADD_ADDRESSES_FAILURE';

export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST';

export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';

export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';
